// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeminiNLSearchPOC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250730174623_insertnewrecords")]
    partial class insertnewrecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EscrowOfficer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "abc",
                            FileName = "deed_001.pdf",
                            Title = "Property Deed"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "xyz",
                            FileName = "mortgage_002.pdf",
                            Title = "Mortgage Agreement"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "abc",
                            FileName = "insurance_003.pdf",
                            Title = "Title Insurance"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "xyz",
                            FileName = "closing_004.pdf",
                            Title = "Closing Statement"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "pqr",
                            FileName = "loan_est_005.pdf",
                            Title = "Loan Estimate"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "abc",
                            FileName = "promo_note_006.pdf",
                            Title = "Promissory Note"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "xyz",
                            FileName = "inspection_007.pdf",
                            Title = "Inspection Report"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "pqr",
                            FileName = "appraisal_008.pdf",
                            Title = "Appraisal Report"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "abc",
                            FileName = "hud_settlement_009.pdf",
                            Title = "HUD-1 Settlement"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "xyz",
                            FileName = "receipt_010.pdf",
                            Title = "Earnest Money Receipt"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "abc",
                            FileName = "addendum_A_011.pdf",
                            Title = "Addendum A"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "pqr",
                            FileName = "disclosures_012.pdf",
                            Title = "Final Disclosures"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "lmn",
                            FileName = "purchase_agree_013.pdf",
                            Title = "Purchase Agreement"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "abc",
                            FileName = "revised_loan_014.pdf",
                            Title = "Revised Loan Statement"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "xyz",
                            FileName = "ho_policy_015.pdf",
                            Title = "Homeowner's Insurance Policy"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "pqr",
                            FileName = "tax_2024_016.pdf",
                            Title = "Tax Statement 2024"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2024, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "lmn",
                            FileName = "water_rights_017.pdf",
                            Title = "Water Rights Agreement"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "abc",
                            FileName = "hoa_bylaws_018.pdf",
                            Title = "HOA Bylaws"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2025, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "pqr",
                            FileName = "survey_report_019.pdf",
                            Title = "Survey Report"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "xyz",
                            FileName = "radon_report_020.pdf",
                            Title = "Radon Inspection Report"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2024, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "lmn",
                            FileName = "lease_agree_021.pdf",
                            Title = "Lease Agreement"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "abc",
                            FileName = "walkthrough_022.pdf",
                            Title = "Final Walkthrough Statement"
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "pqr",
                            FileName = "repair_agree_023.pdf",
                            Title = "Repair Agreement"
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "xyz",
                            FileName = "contingency_024.pdf",
                            Title = "Contingency Removal Form"
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EscrowOfficer = "lmn",
                            FileName = "poa_doc_025.pdf",
                            Title = "Power of Attorney Document"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
